#!/bin/bash
#java -Xms256M -Xmx1024M -classpath  ./fsql.jar:./lib/spring-2.0.jar:./lib/log4j-1.2.15.jar:./lib/hsqldb.jar:./lib/commons-logging-1.1.3.jar pers.ywheel.fsql.FileSQL
java -Xms256M -Xmx1024M -Djava.ext.dirs=./dependencies -cp ./lib/fsql.jar:./configuration pers.ywheel.fsql.FileSQL
